#!/bin/bash

# ------------------------------------------------------------- #
# A shell script for the CIE427 students to run MapReduce jobs  #
# Written by: Muhammad Hamdy AlAref                             #
# Last update: October 7, 2019                                  #
# ------------------------------------------------------------- #
# Usage Instructions                                            #
# 1. Set JAVA_HOME and HADOOP_HOME below to point to their      #
#    correct paths on your machine.                             #
# 2. Add the following line (including the dot at the beginning #
#    to the end of your ~/.bashrc file,                         #
#    . /absolute/path/to/this/script                            #
# 3. Now you can run a map-reduce job by calling the map-reduce #
#    function from any terminal emulator, as well as calling    #
#    any hadoop executable, e.g., hdfs!                         #
# ------------------------------------------------------------- #
# NOTE                                                          #
# The map-reduce job should be located in the <job> directory   #
# as one Java file named MapReduce.java, two Python files named #
# mapper.py and reducer.py or two C++ files nmaed mapper.cpp    #
# and reducer.cpp depending on the first argument; "java",      #
# "python" or "c++", respectively.                              #
# ------------------------------------------------------------- #
# ALL THE PATHS USED IN THE SCRIPT MUST NOT INCLUDE ANY SPACES! #
#                                                               #
# This includes JAVA_HOME, HADOOP_HOME, the current working     #
# directory and the <job> directory!                            #
# ------------------------------------------------------------- #

export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
# export HADOOP_HOME=$(which hadoop)
export PATH=${JAVA_HOME}/bin:${HADOOP_HOME}/bin:${PATH}
export HADOOP_CLASSPATH=${JAVA_HOME}/lib/tools.jar:${HADOOP_HOME}/share/hadoop/tools/lib/*

function map-reduce {
    if [ $# != 2 ]; then
        echo "Usage: map-reduce [java | python | c++] <job>"
        return
    fi

    JOB=$2

    case $1 in
        java)
            ln -s $JOB/MapReduce.java MapReduce.java
            hadoop com.sun.tools.javac.Main MapReduce.java
            rm MapReduce.java
            jar cf job.jar MapReduce*.class
            rm *.class
            hadoop jar job.jar MapReduce $JOB/input $JOB/output
            rm job.jar
        ;;
        python)
            hadoop org.apache.hadoop.streaming.HadoopStreaming \
            -files $JOB/mapper.py,$JOB/reducer.py,$JOB/english.txt,$JOB/nltk.zip \
            -input $JOB/input \
            -output $JOB/output \
            -mapper mapper.py \
            -combiner reducer.py \
            -reducer reducer.py
        ;;
        c++)
            g++ $JOB/mapper.cpp -o mapper
            g++ $JOB/reducer.cpp -o reducer
            hadoop org.apache.hadoop.streaming.HadoopStreaming \
            -files mapper,reducer \
            -input $JOB/input \
            -output $JOB/output \
            -mapper mapper \
            -combiner reducer \
            -reducer reducer
            rm mapper
            rm reducer
        ;;
        *)
            echo "Usage: map-reduce [java | python | c++] <job>"
        ;;
    esac
}
